routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('pages.home');
})->name('home');

Route::get('/company', function () {
    return view('pages.company');
})->name('company');


Route::group(['as'=>'services.'], function () {

    Route::get('/web-development', function () {
        return view('pages.services.web-development');
    })->name('web_development');

    Route::get('/mobile-development', function () {
        return view('pages.services.mobile-development');
    })->name('mobile_development');

    Route::get('/uxui-design', function () {
        return view('pages.services.uxui-design');
    })->name('uxui_design');

    Route::get('/dedicated-team', function () {
        return view('pages.services.dedicated-team');
    })->name('dedicated_team');

});

Route::get('/expertise', function () {
    return view('pages.expertise');
})->name('expertise');

Route::get('/cases', function () {
    return view('pages.cases');
})->name('cases');

Route::get('/cases/tisaapp', function () {
    return view('pages.cases.tissa');
})->name('cases.tisaapp');


Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');


Route::group(['prefix' => '/blog'], function () {
    Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login','Auth\LoginController@login')->name('login');
    Route::post('/logout','Auth\LoginController@logout')->name('logout');

    Route::get('/','PostController@index')->name('blog');
    Route::get('/post/{slug}','PostController@show_by_slug')->name('post');
    //Route::get('/categories','CategoryController@index')->name('categories');
    Route::get('/category/{slug}','CategoryController@show_by_slug')->name('category');

    Route::get('/author/{username}','AuthorController@show')->name('author');
});


Route::group(['prefix' => '/control','middleware'=>'auth','as'=>'control.','namespace' => 'Control'], function () {

    Route::get('/',function(){ return redirect()->route('control.post'); });
    Route::resource('/post', 'PostController')->names(['index' => 'post','create' => 'post.create', 'store' => 'post.store' ,'show' => 'post.show','update' => 'post.update','destroy' => 'post.destroy' ]);
    Route::resource('/category', 'CategoryController')->names(['index' => 'category','create' => 'category.create', 'store' => 'category.store' ,'show' => 'category.show','update' => 'category.update','destroy' => 'category.destroy' ]);

    Route::get('/profile','ProfileController@index')->name('profile');
    Route::put('/profile','ProfileController@update')->name('profile');
});


Route::group(['prefix' => 'admin','as'=>'admin.','namespace' => 'Admin'], function () {

    Route::get('login/','Auth\loginController@showLoginForm')->name('login');
    Route::post('login/','Auth\loginController@login')->name('login');
    Route::post('logout/','Auth\loginController@logout')->name('logout');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/','DashboardController@index')->name('dashboard');

        Route::resource('/image', 'ImageController')->names(['index' => 'image','create' => 'image.create', 'store' => 'image.store' ,'show' => 'image.show','update' => 'image.update','destroy' => 'image.destroy' ]);
        Route::resource('/author', 'AuthorController')->names(['index' => 'author','create' => 'author.create', 'store' => 'author.store' ,'show' => 'author.show','update' => 'author.update','destroy' => 'author.destroy' ]);
        Route::resource('/category', 'CategoryController')->names(['index' => 'category','create' => 'category.create', 'store' => 'category.store' ,'show' => 'category.show','update' => 'category.update','destroy' => 'category.destroy' ]);
        Route::resource('/post', 'PostController')->names(['index' => 'post','create' => 'post.create', 'store' => 'post.store' ,'show' => 'post.show','update' => 'post.update','destroy' => 'post.destroy' ]);
    });

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $guarded = [];
    
    public function image ()
    {
        return $this->belongsTo('App\Image');
    }

    public function posts()
    {
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Image as ImageModel ;
use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::paginate(20);
        return view('admin.pages.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.pages.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $dir = 'images/';
        if( !is_dir( storage_path( Storage::disk('public')->path($dir) ) ) ){
            Storage::disk('public')->makeDirectory($dir,0777);
        }

        $validation = $request->validate([
            'name'  => 'required',
            'slug'  => 'sometimes',
            'image' => 'sometimes|image',
            'status'=> 'required',
        ]);
        // upload image 
        if( $image = $request->file('image') ){
            
            $baseName = Str::random(10);
            $fullName = $baseName.'_category.'.$image->getClientOriginalExtension();
            
            $resize = Image::make( $image )
                ->fit(300,200)
                ->encode('jpg',90);
            Storage::disk('public')->put( $dir . $fullName , $resize);

            // put image info to database
            $ImageModel    = ImageModel::create([ 'path' => $dir . $fullName , 'name' => $image->getClientOriginalName() , 'mim' => $resize->mime() , 'size' => $resize->filesize() ]);
            $ImageModel->save();
            $validation['image_id'] = $ImageModel->id; 
        }
        unset($validation['image']);
        
        $category = Category::create( $validation );
        $category->save();

        return redirect()->route('admin.category')->with('message','Data has been saved successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
        return view('admin.pages.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
        $dir = 'images/';
        if( !is_dir( storage_path( Storage::disk('public')->path($dir) ) ) ){
            Storage::disk('public')->makeDirectory($dir,0777);
        }

        $validation = $request->validate([
            'name'  => 'required',
            'slug'  => 'sometimes',
            'image' => 'sometimes|image',
            //'status'=> 'required',
        ]);
        // upload image 
        if( $image = $request->file('image') ){
            
            if( $category->image ){
                // remove the old image 
                File::delete( Storage::disk('public')->path('/') . $category->image->path );
                $ImageDb = ImageModel::find( $category->image->id );
                $ImageDb->delete();
            }

            // continue code
            $baseName = Str::random(10);
            $fullName = $baseName.'_category.'.$image->getClientOriginalExtension();
            
            $resize = Image::make( $image )
                ->fit(300,200)
                ->encode('jpg',90);
            Storage::disk('public')->put( $dir . $fullName , $resize);

            // put image info to database
            $ImageModel    = ImageModel::create([ 'path' => $dir . $fullName , 'name' => $image->getClientOriginalName() , 'mim' => $resize->mime() , 'size' => $resize->filesize() ]);
            $ImageModel->save();
            $category->image_id = $ImageModel->id;
        }
        unset($validation['image']);
        
        
        $category->name = $request->get('name');
        $category->slug = $request->get('slug');
        $category->status = $request->get('status');
        $category->save();

        return redirect()->route('admin.category')->with('message','Data has been saved successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        // remove the image First
        if( $category->image ){
            File::delete( Storage::disk('public')->path('/') . $category->image->path );
            $ImageDb = ImageModel::find( $category->image->id );
            $ImageDb->delete();
        }

        $category->delete();
        return redirect()->route('admin.category')->with('message','Data has been saved successfully');
    }
}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::where(['status'=>'ACTIVE'])->paginate(20);
        
        return view('pages.blog.category',compact('categories'));
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show_by_slug($slug)
    {
        //
        //dd( $slug );
        $category = Category::with('posts')->where(['slug'=>$slug])->firstOrFail();
        $posts    = $category->posts()->active()->orderBy('created_at', 'desc')->paginate(20);
        //dd( $category );
        return view('pages.blog.category',compact('category','posts'));
    }

}

resources/views/admin/pages/category/create.blade.php
@extends('admin.layouts.app')

@section('title','Create category')

@section('content')

    @if( session('message') )
        <div class="alert alert-success my-2 p-3">
            {{ session('message') }}
        </div>
    @endif

    @if( $errors->any() )
        <div class="alert alert-danger my-2 p-3">
            <ul>
                @foreach( $errors->all() as $error )
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('admin.category.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row mb-2">
            <div class="col-12">
                <input type="file" name="image" class="mb-2" id="image" accept="image/*" onchange="loadFile(event)">
                <br />
                <label for="image">
                    <img id="preview" class="img-thumbnail" src="{{ asset('img/NoImage.png') }}" width="200px"/>
                </label>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="name">name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{ old('name') }}" onkeyup="document.getElementById('slug').value = slugify( this.value )" >
                </div>
            </div>
            <div class="col-12 col-md-6 ">
                <div class="form-group">
                    <label for="">Category name link</label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                          <div class="input-group-text"> ...category/</div>
                        </div>
                        <input name="slug" type="text" class="form-control" id="slug" value="{{ old('slug') }}" placeholder="exemple_category">
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="status">Status </label>
                    <select name="status" class="form-control" id="status">
                        <option value="ACTIVE" {{ old('status') == 'ACTIVE' ? 'selected' : null }} > Active </option>
                        <option value="INACTIVE" {{ old('status') == 'INACTIVE' ? 'selected' : null }} > Inactive </option>
                    </select>
                </div>
            </div>

        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
@endsection


@section('javascript')
<script>
    // Slugify a string
    function slugify(str)
    {
        str = str.replace(/^\s+|\s+$/g, '');

        // Make the string lowercase
        str = str.toLowerCase();

        // Remove accents, swap ñ for n, etc
        var from = "ÁÄÂÀÃÅČÇĆĎÉĚËÈÊẼĔȆÍÌÎÏŇÑÓÖÒÔÕØŘŔŠŤÚŮÜÙÛÝŸŽáäâàãåčçćďéěëèêẽĕȇíìîïňñóöòôõøðřŕšťúůüùûýÿžþÞĐđßÆa·/_,:;";
        var to   = "AAAAAACCCDEEEEEEEEIIIINNOOOOOORRSTUUUUUYYZaaaaaacccdeeeeeeeeiiiinnooooooorrstuuuuuyyzbBDdBAa------";
        for (var i=0, l=from.length ; i<l ; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
        }

        // Remove invalid chars
        str = str.replace(/[^a-z0-9 -]/g, '') 
        // Collapse whitespace and replace by -
        .replace(/\s+/g, '-') 
        // Collapse dashes
        .replace(/-+/g, '-'); 

        return str;
    }

    var loadFile = function(event) {
        var output      = document.getElementById('preview');
        var eventTarget = event.target.files[0] ;
        if( eventTarget ){
            output.src = URL.createObjectURL( eventTarget );
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        }else{
            output.src = 'https://demos.creative-tim.com/vue-black-dashboard-pro/img/image_placeholder.jpg';
        }
    };
</script>
@endsection

resources/views/admin/pages/category/edit.blade.php
@extends('admin.layouts.app')

@section('title','Update category')

@section('content')

    @if( session('message') )
        <div class="alert alert-success my-2 p-3">
            {{ session('message') }}
        </div>
    @endif

    @if( $errors->any() )
        <div class="alert alert-danger my-2 p-3">
            <ul>
                @foreach( $errors->all() as $error )
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('admin.category.update',$category) }}" method="POST" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="row mb-2">
            <div class="col-12">
                <input type="file" name="image" class="mb-2" id="image" accept="image/*" onchange="loadFile(event)">
                <br />
                <label for="image">
                    <img id="preview" class="img-thumbnail" src="{{ $category->image ? asset('storage/'. $category->image->path ) : asset('img/NoImage.png') }}" width="200px"/>
                </label>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="name">name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{ old('name') ?? $category->name }}"  >
                </div>
            </div>
            <div class="col-12 col-md-6 ">
                <div class="form-group">
                    <label for="">Category name link</label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text"> ...category/</div>
                        </div>
                        <input name="slug" type="text" class="form-control" id="slug" value="{{ old('slug') ?? $category->slug }}" placeholder="exemple_category">
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="status">Status </label>
                    <select name="status" class="form-control" id="status">
                        <option value="ACTIVE" {{ $category->status == 'ACTIVE' ? 'selected' : null }} > Active </option>
                        <option value="INACTIVE" {{ $category->status == 'INACTIVE' ? 'selected' : null }} > Inactive </option>
                    </select>
                </div>
            </div>

        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
@endsection


@section('javascript')
<script>

    var loadFile = function(event) {
        var output      = document.getElementById('preview');
        var eventTarget = event.target.files[0] ;
        if( eventTarget ){
            output.src = URL.createObjectURL( eventTarget );
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        }else{
            output.src = 'https://demos.creative-tim.com/vue-black-dashboard-pro/img/image_placeholder.jpg';
        }
    };
</script>
@endsection

resources/views/admin/pages/category/index.blade.php
@extends('admin.layouts.app')

@section('title','Categories')

@section('content')

    @if( session('message') )
        <div class="alert alert-success my-2 p-3">
            {{ session('message') }}
        </div>
    @endif

    @if( $errors->any() )
        <div class="alert alert-danger my-2 p-3">
            <ul>
                @foreach( $errors->all() as $error )
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th width="150px"> <a class="btn btn-sm btn-primary" href="{{ route('admin.category.create') }}"> <i class="fas fa-plus"></i> </a> </th>
                <th width="50px" > </th>
                <th> Name </th>
                <th> Articles </th>
            </tr> 
        </thead>
        <tbody>
            @foreach( $categories as $category )
                <tr class="{{ $category->status == 'PENDING' ? 'table-warning' : null }} {{ $category->status == 'INACTIVE' ? 'table-danger' : null }}">
                    <td>
                        <a href="{{ route('category', $category->slug ) }}" class="mr-2 btn btn-sm btn-primary"> <i class="fas fa-external-link-alt"></i> <a>
                        <a href="{{ route('admin.category.edit', $category ) }}" class="mr-1 btn btn-sm btn-info"> <i class="fas fa-pencil-alt"></i> <a>
                        <label class="mr-1 mt-2 btn btn-sm btn-danger"> <i class="far fa-trash-alt"></i> <label>
                        <form action="{{ route('admin.category.destroy',$category) }}" method="POST" class="d-none" >
                            @method('DELETE')
                            @csrf
                            <input type="submit" id="remove_item"  />
                        </form>
                    </td>
                    <td> @if( $category->image ) <img src="{{ asset('storage/'. $category->image->path ) }}" height="30"/> @endif </td>
                    <td> {{ $category->name }} </td>
                    <td> {{ $category->posts()->count() }} </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $categories->links() }}
    
@endsection