routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('pages.home');
})->name('home');

Route::get('/company', function () {
    return view('pages.company');
})->name('company');


Route::group(['as'=>'services.'], function () {

    Route::get('/web-development', function () {
        return view('pages.services.web-development');
    })->name('web_development');

    Route::get('/mobile-development', function () {
        return view('pages.services.mobile-development');
    })->name('mobile_development');

    Route::get('/uxui-design', function () {
        return view('pages.services.uxui-design');
    })->name('uxui_design');

    Route::get('/dedicated-team', function () {
        return view('pages.services.dedicated-team');
    })->name('dedicated_team');

});

Route::get('/expertise', function () {
    return view('pages.expertise');
})->name('expertise');

Route::get('/cases', function () {
    return view('pages.cases');
})->name('cases');

Route::get('/cases/tisaapp', function () {
    return view('pages.cases.tissa');
})->name('cases.tisaapp');


Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');


Route::group(['prefix' => '/blog'], function () {
    Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login','Auth\LoginController@login')->name('login');
    Route::post('/logout','Auth\LoginController@logout')->name('logout');

    Route::get('/','PostController@index')->name('blog');
    Route::get('/post/{slug}','PostController@show_by_slug')->name('post');
    //Route::get('/categories','CategoryController@index')->name('categories');
    Route::get('/category/{slug}','CategoryController@show_by_slug')->name('category');

    Route::get('/author/{username}','AuthorController@show')->name('author');
});


Route::group(['prefix' => '/control','middleware'=>'auth','as'=>'control.','namespace' => 'Control'], function () {

    Route::get('/',function(){ return redirect()->route('control.post'); });
    Route::resource('/post', 'PostController')->names(['index' => 'post','create' => 'post.create', 'store' => 'post.store' ,'show' => 'post.show','update' => 'post.update','destroy' => 'post.destroy' ]);
    Route::resource('/category', 'CategoryController')->names(['index' => 'category','create' => 'category.create', 'store' => 'category.store' ,'show' => 'category.show','update' => 'category.update','destroy' => 'category.destroy' ]);

    Route::get('/profile','ProfileController@index')->name('profile');
    Route::put('/profile','ProfileController@update')->name('profile');
});


Route::group(['prefix' => 'admin','as'=>'admin.','namespace' => 'Admin'], function () {

    Route::get('login/','Auth\loginController@showLoginForm')->name('login');
    Route::post('login/','Auth\loginController@login')->name('login');
    Route::post('logout/','Auth\loginController@logout')->name('logout');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/','DashboardController@index')->name('dashboard');

        Route::resource('/image', 'ImageController')->names(['index' => 'image','create' => 'image.create', 'store' => 'image.store' ,'show' => 'image.show','update' => 'image.update','destroy' => 'image.destroy' ]);
        Route::resource('/author', 'AuthorController')->names(['index' => 'author','create' => 'author.create', 'store' => 'author.store' ,'show' => 'author.show','update' => 'author.update','destroy' => 'author.destroy' ]);
        Route::resource('/category', 'CategoryController')->names(['index' => 'category','create' => 'category.create', 'store' => 'category.store' ,'show' => 'category.show','update' => 'category.update','destroy' => 'category.destroy' ]);
        Route::resource('/post', 'PostController')->names(['index' => 'post','create' => 'post.create', 'store' => 'post.store' ,'show' => 'post.show','update' => 'post.update','destroy' => 'post.destroy' ]);
    });

});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Image as ImageModel ;
use App\User;
use Illuminate\Http\Request;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $authors = User::with(['image','posts'])->paginate(20);
        return view('admin.pages.author.index',compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.pages.author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $dir = 'images/';
        if( !is_dir( storage_path( Storage::disk('public')->path($dir) ) ) ){
            Storage::disk('public')->makeDirectory($dir,0777);
        }

        $validation = $request->validate([
            'name'      => 'required',
            'username'  => 'required',
            'email'     => 'required',
            'password'  => 'required',
            'image'     => 'sometimes|image',
            'is_super'  => 'required',
            'status'    => 'required',
        ]);

        // upload image 
        if( $image = $request->file('image') ){
            
            $baseName = Str::random(10);
            $fullName = $baseName.'_author.'.$image->getClientOriginalExtension();
            
            $resize = Image::make( $image )
                ->fit(300)
                ->encode('jpg',90);
            Storage::disk('public')->put( $dir . $fullName , $resize);

            // put image info to database
            $ImageModel    = ImageModel::create([ 'path' => $dir . $fullName , 'name' => $image->getClientOriginalName() , 'mim' => $resize->mime() , 'size' => $resize->filesize() ]);
            $ImageModel->save();
            $validation['image_id'] = $ImageModel->id; 
        }
        unset($validation['image']);

        $validation['password'] = \Hash::make( $request->get('password') ); 
        //dd( $validation );
        $author = User::create($validation);
        $author->save();
        
        return redirect()->route('admin.author')->with('message','Data has been saved successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $author)
    {
        //
        return view('admin.pages.author.edit',compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $author)
    {
        //

        $dir = 'images/';
        if( !is_dir( storage_path( Storage::disk('public')->path($dir) ) ) ){
            Storage::disk('public')->makeDirectory($dir,0777);
        }

        $validation = $request->validate([
            'name'      => 'required',
            'username'  => 'required',
            'email'     => 'required',
            'password'  => 'sometimes',
            'image'     => 'sometimes|image',
            'is_super'  => 'required',
            'status'    => 'required',
        ]);

        // upload image 
        if( $image = $request->file('image') ){
            
             // remove the old image
            if( $author->image ){
                File::delete( Storage::disk('public')->path('/') . $author->image->path );
                $ImageDb = ImageModel::find( $author->image->id );
                $ImageDb->delete();
            }

            $baseName = Str::random(10);
            $fullName = $baseName.'_author.'.$image->getClientOriginalExtension();
            
            $resize = Image::make( $image )
                ->fit(300)
                ->encode('jpg',90);
            Storage::disk('public')->put( $dir . $fullName , $resize);

            // put image info to database
            $ImageModel    = ImageModel::create([ 'path' => $dir . $fullName , 'name' => $image->getClientOriginalName() , 'mim' => $resize->mime() , 'size' => $resize->filesize() ]);
            $ImageModel->save();

            $author->image_id = $ImageModel->id;
        }

        
        if( $request->get('password') ){
            $author->password = \Hash::make( $request->get('password') );
        }

        $author->name     = $request->get('name');
        $author->email    = $request->get('email');
        $author->username = $request->get('username');
        $author->is_super = $request->get('is_super');
        $author->status   = $request->get('status');
        $author->save();

        return redirect()->route('admin.author')->with('message','Data has been saved successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $author)
    {
        //

        if( $author->image ){
            File::delete( Storage::disk('public')->path('/') . $author->image->path );
            $ImageDb = ImageModel::find( $author->image->id );
            $ImageDb->delete();
        }

        $author->delete();

        return redirect()->route('admin.author')->with('message','Data has been saved successfully');
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($username)
    {
        //
        $user  = User::where(['username'=>$username])->firstOrFail();
        $posts = $user->posts()->active()->orderBy('created_at', 'desc')->paginate(20);
        return view('pages.author',compact('user','posts'));
    }

}

resources/views/admin/pages/author/create.blade.php
@extends('admin.layouts.app')

@section('title','Create authors')

@section('content')

    @if( session('message') )
        <div class="alert alert-success my-2 p-3">
            {{ session('message') }}
        </div>
    @endif

    @if( $errors->any() )
        <div class="alert alert-danger my-2 p-3">
            <ul>
                @foreach( $errors->all() as $error )
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('admin.author.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row mb-2">
            <div class="col-12">
                <input type="file" name="image" class="mb-2" id="image" accept="image/*" onchange="loadFile(event)">
                <br />
                <label for="image">
                    <img id="preview" class="img-thumbnail" src="{{ asset('img/NoProfile.png') }}" width="200px"/>
                </label>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="name">Full name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{ old('name') }}"  >
                </div>
            </div>
            <div class="col-12 col-md-6 ">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input name="username" type="text" class="form-control" id="username" value="{{ old('username') }}" >
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input name="email" type="text" class="form-control" id="email" value="{{ old('email') }}" >
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="password">Password</label>
                    <input name="password" type="text" class="form-control" id="password" value="{{ old('password') ?? 'almossaid' }}" >
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="status">Status </label>
                    <select name="status" class="form-control" id="status">
                        <option value="ACTIVE"> Active </option>
                        <option value="PENDING"> Pending </option>
                        <option value="INACTIVE"> Inactive </option>
                    </select>
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="is_super">Is super author </label>
                    <select name="is_super" class="form-control" id="is_super">
                        <option value="0"> Simple author </option>
                        <option value="1"> Super author </option>
                    </select>
                </div>
            </div>

        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
@endsection


@section('javascript')
<script>

    var loadFile = function(event) {
        var output      = document.getElementById('preview');
        var eventTarget = event.target.files[0] ;
        if( eventTarget ){
            output.src = URL.createObjectURL( eventTarget );
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        }else{
            output.src = 'https://demos.creative-tim.com/vue-black-dashboard-pro/img/image_placeholder.jpg';
        }
    };
</script>
@endsection

resources/views/admin/pages/author/edit.blade.php
@extends('admin.layouts.app')

@section('title','Update author')

@section('content')

    @if( session('message') )
        <div class="alert alert-success my-2 p-3">
            {{ session('message') }}
        </div>
    @endif

    @if( $errors->any() )
        <div class="alert alert-danger my-2 p-3">
            <ul>
                @foreach( $errors->all() as $error )
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('admin.author.update',$author) }}" method="POST" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="row mb-2">
            <div class="col-12">
                <input type="file" name="image" class="mb-2" id="image" accept="image/*" onchange="loadFile(event)">
                <br />
                <label for="image">
                    <img id="preview" class="img-thumbnail" src="{{ $author->image ? asset('storage/'. $author->image->path ) : asset('img/NoProfile.png') }}" width="200px"/>
                </label>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="name">Full name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{ old('name') ?? $author->name }}"  >
                </div>
            </div>
            <div class="col-12 col-md-6 ">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input name="username" type="text" class="form-control" id="username" value="{{ old('username') ?? $author->username }}" >
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input name="email" type="text" class="form-control" id="email" value="{{ old('email') ?? $author->email }}" >
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="password">Password</label>
                    <input name="password" type="password" class="form-control" id="password" >
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="status">Status </label>
                    <select name="status" class="form-control" id="status">
                        <option value="ACTIVE" {{ $author->status == 'ACTIVE' ? 'selected' : null }} > Active </option>
                        <option value="PENDING" {{ $author->status == 'PENDING' ? 'selected' : null }} > Pending </option>
                        <option value="INACTIVE" {{ $author->status == 'INACTIVE' ? 'selected' : null }} > Inactive </option>
                    </select>
                </div>
            </div>

            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label for="is_super">Is super author </label>
                    <select name="is_super" class="form-control" id="is_super">
                        <option value="0" {{ !$author->is_super ? 'selected' : null }} > Simple author </option>
                        <option value="1" {{ $author->is_super ? 'selected' : null }} > Super author </option>
                    </select>
                </div>
            </div>

        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
@endsection


@section('javascript')
<script>

    var loadFile = function(event) {
        var output      = document.getElementById('preview');
        var eventTarget = event.target.files[0] ;
        if( eventTarget ){
            output.src = URL.createObjectURL( eventTarget );
            output.onload = function() {
                URL.revokeObjectURL(output.src) // free memory
            }
        }else{
            output.src = 'https://demos.creative-tim.com/vue-black-dashboard-pro/img/image_placeholder.jpg';
        }
    };
</script>
@endsection

resources/views/admin/pages/author/index.blade.php
@extends('admin.layouts.app')

@section('title','Authors')

@section('content')

    @if( session('message') )
        <div class="alert alert-success my-2 p-3">
            {{ session('message') }}
        </div>
    @endif

    @if( $errors->any() )
        <div class="alert alert-danger my-2 p-3">
            <ul>
                @foreach( $errors->all() as $error )
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th width="150px"> <a class="btn btn-sm btn-primary" href="{{ route('admin.author.create') }}"> <i class="fas fa-plus"></i> </a> </th>
                <th width="50px" > </th>
                <th> Name </th>
                <th> username </th>
                <th> Email address </th>
                <th> Articles </th>
            </tr> 
        </thead>
        <tbody>
            @foreach( $authors as $author )
                <tr class="{{ $author->status == 'PENDING' ? 'table-warning' : null }} {{ $author->status == 'INACTIVE' ? 'table-danger' : null }}">
                    <td>
                        <a href="{{ route('author', $author->username ) }}" class="mr-2 btn btn-sm btn-primary"> <i class="fas fa-external-link-alt"></i> <a>
                        <a href="{{ route('admin.author.edit', $author ) }}" class="mr-1 btn btn-sm btn-info"> <i class="fas fa-pencil-alt"></i> <a>
                        <label class="mr-1 mt-2 btn btn-sm btn-danger"> <i class="far fa-trash-alt"></i> <label>
                        <form action="{{ route('admin.author.destroy',$author) }}" method="POST" class="d-none" >
                            @method('DELETE')
                            @csrf
                            <input type="submit" id="remove_item"  />
                        </form>
                    </td>
                    <td> @if( $author->image ) <img src="{{ asset('storage/'. $author->image->path ) }}" height="30"/> @endif </td>
                    <td> @if( $author->is_super ) <i class="fas fa-user-tie"></i> @endif {{ $author->name }} </td>
                    <td> {{ $author->username }} </td>
                    <td> {{ $author->email }} </td>
                    <td> {{ $author->posts()->count() }} </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $authors->links() }}
    
@endsection