routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('pages.home');
})->name('home');

Route::get('/company', function () {
    return view('pages.company');
})->name('company');


Route::group(['as'=>'services.'], function () {

    Route::get('/web-development', function () {
        return view('pages.services.web-development');
    })->name('web_development');

    Route::get('/mobile-development', function () {
        return view('pages.services.mobile-development');
    })->name('mobile_development');

    Route::get('/uxui-design', function () {
        return view('pages.services.uxui-design');
    })->name('uxui_design');

    Route::get('/dedicated-team', function () {
        return view('pages.services.dedicated-team');
    })->name('dedicated_team');

});

Route::get('/expertise', function () {
    return view('pages.expertise');
})->name('expertise');

Route::get('/cases', function () {
    return view('pages.cases');
})->name('cases');

Route::get('/cases/tisaapp', function () {
    return view('pages.cases.tissa');
})->name('cases.tisaapp');


Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');


Route::group(['prefix' => '/blog'], function () {
    Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login','Auth\LoginController@login')->name('login');
    Route::post('/logout','Auth\LoginController@logout')->name('logout');

    Route::get('/','PostController@index')->name('blog');
    Route::get('/post/{slug}','PostController@show_by_slug')->name('post');
    //Route::get('/categories','CategoryController@index')->name('categories');
    Route::get('/category/{slug}','CategoryController@show_by_slug')->name('category');

    Route::get('/author/{username}','AuthorController@show')->name('author');
});


Route::group(['prefix' => '/control','middleware'=>'auth','as'=>'control.','namespace' => 'Control'], function () {

    Route::get('/',function(){ return redirect()->route('control.post'); });
    Route::resource('/post', 'PostController')->names(['index' => 'post','create' => 'post.create', 'store' => 'post.store' ,'show' => 'post.show','update' => 'post.update','destroy' => 'post.destroy' ]);
    Route::resource('/category', 'CategoryController')->names(['index' => 'category','create' => 'category.create', 'store' => 'category.store' ,'show' => 'category.show','update' => 'category.update','destroy' => 'category.destroy' ]);

    Route::get('/profile','ProfileController@index')->name('profile');
    Route::put('/profile','ProfileController@update')->name('profile');
});


Route::group(['prefix' => 'admin','as'=>'admin.','namespace' => 'Admin'], function () {

    Route::get('login/','Auth\loginController@showLoginForm')->name('login');
    Route::post('login/','Auth\loginController@login')->name('login');
    Route::post('logout/','Auth\loginController@logout')->name('logout');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/','DashboardController@index')->name('dashboard');

        Route::resource('/image', 'ImageController')->names(['index' => 'image','create' => 'image.create', 'store' => 'image.store' ,'show' => 'image.show','update' => 'image.update','destroy' => 'image.destroy' ]);
        Route::resource('/author', 'AuthorController')->names(['index' => 'author','create' => 'author.create', 'store' => 'author.store' ,'show' => 'author.show','update' => 'author.update','destroy' => 'author.destroy' ]);
        Route::resource('/category', 'CategoryController')->names(['index' => 'category','create' => 'category.create', 'store' => 'category.store' ,'show' => 'category.show','update' => 'category.update','destroy' => 'category.destroy' ]);
        Route::resource('/post', 'PostController')->names(['index' => 'post','create' => 'post.create', 'store' => 'post.store' ,'show' => 'post.show','update' => 'post.update','destroy' => 'post.destroy' ]);
    });

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

class Post extends Model
{
    //
    protected $guarded = [];

    public function user ()
    {
        return $this->belongsTo('App\User');
    }

    public function image ()
    {
        return $this->belongsTo('App\Image');
    }
    
    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag','tag_post');
    }

    public function scopeActive( $query )
    {
        return $query->where(['status'=>'ACTIVE']);
    }

    public function getDescriptionAttribute()
    {
        $breaks = explode('<!-- pagebreak -->', $this->body );
        return trim( strip_tags( ( count($breaks) > 1 ? $breaks[0] : null ) ) );
    }
    public function getTimeAttribute()
    {
        return Carbon::parse($this->created_at)->isoFormat('LLLL');
    }

    public function getTimeAgoAttribute()
    {
        return Carbon::parse($this->created_at)->diffForHumans();
    }
    /*
    public function getTagsAttribute()
    {
        return explode( ',' , $this->attributes['tags'] );
    }

    public function getKeywordsAttribute()
    {
        return implode( ',' , $this->tags );
    }
    */
    
    

}

resources/views/layouts/partials/call.blade.php
<div class="moussaid-call-to-action-area shape-position ax-section-gap bg-color-darkest">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="moussaid-call-to-action">
                    <div class="section-title text-center">
                        <span class="sub-title primary-color wow" data-splitting>Let's work together</span>
                        <h2 class="title wow whitecolor" data-splitting>Need a successful project?</h2>
                        <a class="moussaid-button btn-large btn-transparent" href="#"><span
                                class="button-text ">Estimate Project</span><span class="button-icon"></span></a>
                        <div class="callto-action">
                            <span class="text wow whitecolor" data-splitting>Or call us now</span>
                            <span class="wow whitecolor" data-splitting><i class="fas fa-phone-alt"></i> <a
                                    class="whitecolor" href="#">+212 670-039289</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/partials/expertise.blade.php
<div class="moussaid-service-area ax-section-gap backgound-dots">
    <div class="container">

        <div class="row">

            <div class="col-lg-5 col-12">
                <div class="section-title text-left">
                    <span class="sub-title extra08-color wow" data-splitting>Our Expertise</span>
                    <h2 class="title wow" data-splitting>Who We Are?</h2>
                    <p class="subtitle-2 wow pr--0" data-splitting>We believe in the power of design in software
                        development. We thrive on building relationships and helping good people and
                        organizations succeed through a collaborative process.
                    </p>
                    <div class="view-all-portfolio-button mt--40">
                        <a class="moussaid-button btn-large btn-transparent" href="#"><span class="button-text">Get
                                to Know Us Better</span><span class="button-icon"></span></a>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 offset-xl-1 col-12 mt_md--40 mt_sm--40">
                <div class="row">

                    <div class="col-lg-6 col-md-6 col-sm-6 col-6">
                        <div class="almoussaid-expertise text-left counter-1 move-up wow">
                            <div class="inner">
                                <div class="icon">
                                    <img src="{{asset('frontend/assets/images/icons/e-commerce.svg')}}"
                                        alt="Icon Images">
                                </div>

                                <div class="icon-go">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14.012" height="14.012"
                                        viewBox="0 0 14.012 14.012">
                                        <g id="Icon_feather-arrow-up-right" data-name="Icon feather-arrow-up-right"
                                            transform="translate(-9.086 -9.086)">
                                            <path id="Path_34125" data-name="Path 34125" d="M10.5,21.684,21.684,10.5"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                            <path id="Path_34126" data-name="Path 34126" d="M10.5,10.5H21.684V21.684"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                        </g>
                                    </svg>
                                </div>

                                <div class="content">
                                    <h4 class="title">E-Commerce</h4>
                                    <p>Online stores, retail marketplaces and ecommerce startups.</p>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-6 col-md-6 col-sm-6 col-6">
                        <div class="almoussaid-expertise text-left color-style-two mt--60 mt_mobile--40 move-up wow">
                            <div class="inner">
                                <div class="icon">
                                    <img src="{{asset('frontend/assets/images/icons/e-learning.svg')}}"
                                        alt="Icon Images">
                                </div>

                                <div class="icon-go">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14.012" height="14.012"
                                        viewBox="0 0 14.012 14.012">
                                        <g id="Icon_feather-arrow-up-right" data-name="Icon feather-arrow-up-right"
                                            transform="translate(-9.086 -9.086)">
                                            <path id="Path_34125" data-name="Path 34125" d="M10.5,21.684,21.684,10.5"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                            <path id="Path_34126" data-name="Path 34126" d="M10.5,10.5H21.684V21.684"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                        </g>
                                    </svg>
                                </div>

                                <div class="content">
                                    <h4 class="title">E-learning</h4>
                                    <p>Online training, learning management systems, and mobile apps.</p>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-6 col-md-6 col-sm-6 col-6">
                        <div class="almoussaid-expertise text-left color-style-three mt_mobile--40 move-up wow">
                            <div class="inner">
                                <div class="icon">
                                    <img src="{{asset('frontend/assets/images/icons/travel.svg')}}" alt="Icon Images">
                                </div>

                                <div class="icon-go">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14.012" height="14.012"
                                        viewBox="0 0 14.012 14.012">
                                        <g id="Icon_feather-arrow-up-right" data-name="Icon feather-arrow-up-right"
                                            transform="translate(-9.086 -9.086)">
                                            <path id="Path_34125" data-name="Path 34125" d="M10.5,21.684,21.684,10.5"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                            <path id="Path_34126" data-name="Path 34126" d="M10.5,10.5H21.684V21.684"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                        </g>
                                    </svg>
                                </div>

                                <div class="content">
                                    <h4 class="title">Travel & Hospitality</h4>
                                    <p>Solutions for tour operators, travel & hospitality agencies and corporate
                                        clients.</p>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-lg-6 col-md-6 col-sm-6 col-6">
                        <div class="almoussaid-expertise text-left color-style-four mt--60 mt_mobile--40 move-up wow">
                            <div class="inner">
                                <div class="icon">
                                    <img src="{{asset('frontend/assets/images/icons/indusrty.svg')}}" alt="Icon Images">
                                </div>

                                <div class="icon-go">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14.012" height="14.012"
                                        viewBox="0 0 14.012 14.012">
                                        <g id="Icon_feather-arrow-up-right" data-name="Icon feather-arrow-up-right"
                                            transform="translate(-9.086 -9.086)">
                                            <path id="Path_34125" data-name="Path 34125" d="M10.5,21.684,21.684,10.5"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                            <path id="Path_34126" data-name="Path 34126" d="M10.5,10.5H21.684V21.684"
                                                fill="none" stroke="#9D9D9D" stroke-linecap="round"
                                                stroke-linejoin="round" stroke-width="2" />
                                        </g>
                                    </svg>
                                </div>

                                <div class="content">
                                    <h4 class="title">Industry</h4>
                                    <p>Outsourcing software development services to beat off market competition
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

resources/views/layouts/partials/footer.blade.php
<footer class="moussaid-footer footer-default theme-gradient-2">
    <div class="bg_image--2">
        <div class="ft-social-icon-wrapper ax-section-gapTop">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="ft-social-share d-flex justify-content-center liststyle flex-wrap">
                            <li><a target="_blank" href="https://www.facebook.com/almossaidweb"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a target="_blank" href="https://www.instagram.com/almossaidweb/"><i class="fab fa-instagram"></i></a></li>
                            <li><a target="_blank" href="https://www.linkedin.com/company/almossaid"><i class="fab fa-linkedin-in"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-top ax-section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="footer-widget-item moussaid-border-right">
                            <h2>Get in touch!</h2>
                            <p>Subscribe</p>
                            <div class="moussaid-newsletter">
                                <form class="newsletter-form" action="#">
                                    <input type="email" placeholder="Email">
                                    <a class="moussaid-button btn-transparent" href="#"><span
                                            class="button-text">Subscribe</span><span class="button-icon"></span></a>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6 col-12 mt_mobile--30">
                        <div class="footer-widget-item">
                            <h6 class="title">Services</h6>
                            <div class="footer-menu-container">
                                <ul class="ft-menu liststyle link-hover">
                                    <li><a href="{{ route('services.web_development') }}">Web Development</a></li>
                                    <li><a href="{{ route('services.mobile_development') }}">Mobile App Development</a></li>
                                    <li><a href="{{ route('services.uxui_design') }}">UX/UI Design</a></li>
                                    <li><a href="{{ route('services.dedicated_team') }}">Dedicated team</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-6 col-md-6 col-sm-6 col-12 mt_lg--30 mt_md--30 mt_sm--30">
                        <div class="footer-widget-item">
                            <h6 class="title">Resourses</h6>
                            <div class="footer-menu-container">
                                <ul class="ft-menu liststyle link-hover">
                                    {{-- <li><a href="/blog">Blog</a></li> --}}
                                    <li><a href="{{ route('cases') }}">Case Studies</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-1 col-lg-6 col-md-6 col-sm-6 col-12 mt_lg--30 mt_md--30 mt_sm--30">
                        <div class="footer-widget-item widget-support">
                            <h6 class="title">Support</h6>
                            <div class="footer-menu-container">
                                <ul class="ft-menu liststyle link-hover">
                                    <li><a href="{{ route('contact') }}">Contact</a></li>
                                    <li><a href="#soon">Privacy Policy</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright copyright-default">
            <div class="container">
                <div class="row row--0 ptb--20 moussaid-basic-thine-line">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                        <div class="inner text-center text-md-left">
                            <p>© 2017 - {{ date('Y') }}. All rights reserved. <img src="{{ asset('frontend/assets/images/shape/s1.svg') }}" alt="Almossaid" height="30" /> S.A.M.W.SERVICES LLC </p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                        <div class="quick-contact">
                            <ul class="link-hover d-flex justify-content-center justify-content-md-end liststyle">
                                <li><a href="#soonnn">Terms of Use</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>



<style>
    @keyframes shadow-pulse {
        0% {
            box-shadow: 0 0 0 0px rgba(0, 0, 0, 0.2);
        }

        100% {
            box-shadow: 0 0 0 35px rgba(0, 0, 0, 0);
        }
    }

    @keyframes shadow-pulse-big {
        0% {
            box-shadow: 0 0 0 0px rgba(0, 0, 0, 0.1);
        }

        100% {
            box-shadow: 0 0 0 70px rgba(0, 0, 0, 0);
        }
    }

    .notif-whatsapp {
        background-color: #1ee62e;

        height: 4rem;
        width: 4rem;
        position: fixed;
        bottom: 3rem;
        left: 3rem;
        border-radius: 50%;
        z-index: 2000;
        box-shadow: 0 1rem 3rem rgba(0, 0, 0, 0.2);
        text-align: center;
        cursor: pointer;
        animation: shadow-pulse 1s infinite;
    }

    .notif-whatsapp .icon {
        height: 4rem;
        width: 4rem;
        line-height: 4rem;
        position: absolute;
        top: .4rem;
        left: 0rem;
        border-radius: 50%;
        z-index: 2000;
        /* box-shadow: 0 1rem 3rem rgba(0,0,0,0.2); */
        text-align: center;
        cursor: pointer;
    }
</style>

<div class="notif-whatsapp">
    <div class="icon">
        <a href="https://api.whatsapp.com/send?phone=+212670039289" target="_blank"><i
                class="fab fa-whatsapp fa-2x" style="color:#fff"></i></a>
    </div>
</div>

resources/views/layouts/partials/header.blade.php
<header class="ax-header haeder-default light-logo-version header-transparent moussaid-header-sticky">
    <div class="header-wrapper">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-6 col-sm-6 col-8">
                    <div class="logo">
                        <a href="{{ route('home') }}">
                            <img src="{{asset('frontend/assets/images/shape/s1.svg')}}" alt='Almossaid' width="76px" />
                        </a>
                    </div>
                </div>
                <div class="col-lg-9 col-md-6 col-sm-6 col-4">
                    <div class="mainmenu-wrapepr">
                        <nav class="mainmenu-nav d-none d-lg-block">
                            <ul class="mainmenu">
                                <li class="has-dropdown"><a href="#">Services</a>
                                    <ul class="moussaid-submenu">
                                        <li><a href="{{ route('services.web_development') }}">Web Development</a></li>
                                        <li><a href="{{ route('services.mobile_development') }}">Mobile Development</a></li>
                                        <li><a href="{{ route('services.uxui_design') }}">UX/UI Design</a></li>
                                        <li><a href="{{ route('services.dedicated_team') }}">Dedicated team</a></li>
                                    </ul>
                                </li>
                                <li><a href="{{ route('cases') }}">Portfolio</a>

                                </li>

                                <li><a href="{{ route('expertise') }}">Expertise</a></li>
                                <li><a href="{{ route('company') }}">Company</a></li>

                                {{-- <li><a href="/blog">Blog</a></li> --}}

                            </ul>
                        </nav>
                        <div class="ax-header-button ml--40 ml_lg--10 d-none d-sm-block">
                            <a class="moussaid-button btn-solid btn-extra02-color" href="{{ route('contact') }}"><span
                                    class="button-text">Contact us</span><span class="button-icon"></span></a>
                        </div>
                        <div class="ax-menubar popup-navigation-activation d-block d-lg-none ml_sm--20 ml_md--20">
                            <div>
                                <i></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="popup-mobile-manu">
    <div class="inner">
        <div class="mobileheader">
            <div class="logo">
                <a href="{{ route('home') }}">
                    <img src="{{asset('frontend/assets/images/shape/s1.svg')}}" alt="Almossaid" width="70px">
                </a>
            </div>
            <a class="close-menu" href="#"></a>
        </div>
        <div class="menu-item">
            <ul class="mainmenu-item">
                <li><a href="{{ route('home') }}">Home</a></li>
                <li class="has-children"><a href="#">Services</a>
                    <ul class="submenu">
                        <li><a href="{{ route('services.web_development') }}">Web Development</a></li>
                        <li><a href="{{ route('services.mobile_development') }}">Mobile Development</a></li>
                        <li><a href="{{ route('services.uxui_design') }}">UX/UI Design</a></li>
                        <li><a href="{{ route('services.dedicated_team') }}">Dedicated team</a></li>
                    </ul>
                </li>
                <li><a href="{{ route('expertise') }}">Expertise</a></li>
                <li><a href="{{ route('company') }}">Company</a></li>
                {{-- <li><a href="/blog">Blog</a></li> --}}

                <li><a href="{{ route('contact') }}">Contact</a></li>
            </ul>
        </div>

    </div>
</div>

resources/views/layouts/partials/latestposts.blade.php
<div class="moussaid-blog-area ax-section-gap bg-color-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title text-left">
                    <span class="sub-title primary-color">Blog</span>
                    <h2 class="title">Our latest articles and publications</h2>

                </div>
            </div>
        </div>
        <div class="row blog-list-wrapper mt--20">

            @foreach ($latestposts as $post)
            <div class="col-lg-6 col-md-6 col-12">
                <div class="moussaid-blog moussaid-control mt--40 active move-up wow">
                    <div class="content">
                        <div class="content-wrap paralax-image">
                            <div class="inner">
                                @foreach( $post->categories as $category )
                                <a href="{{ route('category', ( $category->slug ?? $category ) ) }}"><span
                                        class="category">{{ $category->name }}</span></a>
                                @endforeach

                                <h5 class="title"><a href="{{ route('post', $post->slug ) }}">{{ $post->title }}</a>
                                </h5>
                                <p> {!! substr(strip_tags($post->description), 0, 100) !!}...</p>
                                <small>{{ $post->timeAgo }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="thumbnail">
                        <div class="image">
                            <img src="{{ asset('storage/'. $post->image->path ) }}" alt="Blog images">
                        </div>
                    </div>
                </div>
            </div>
            @endforeach




        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <a class="moussaid-button mt--30  btn-large btn-transparent" href="#"><span class="button-text">All
                        posts</span><span class="button-icon"></span></a>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/partials/slide.blade.php
<div class="moussaid-slider-area moussaid-slide-activation">
    <div class="moussaid-slide banner-technology bg_image bg_image--1 ">
        <div class="container">
            <div class="row align-items-center pt_md--60 mt_sm--60">
                <div class="col-lg-7 col-12 order-2 order-lg-1">
                    <div class="content pt_md--30 pt_sm--30">
                        <h1 class="moussaid-display-1 prim-color wow slideFadeInUp" data-wow-duration="1s"
                            data-wow-delay="500ms">Where others see problems<br />
                            We see solutions.</h1>
                        <h2 class="moussaid-display-3 second-color wow slideFadeInUp" data-wow-duration="1s"
                            data-wow-delay="500ms">Building reliable software solutions for your business.
                        </h2>
                        <p class="subtitle-3 wow slideFadeInUp" data-wow-duration="1s" data-wow-delay="800ms">
                            Almossaid is a professional software development outsourcing company. We strive to
                            succeed, we crave innovation, we make a difference
                        </p>
                        <a class="moussaid-button btn-large btn-transparent wow slideFadeInUp" data-wow-duration="1s"
                            data-wow-delay="1300ms" href="/contact"><span class="button-text">ESTIMATE PROJECT</span><span
                                class="button-icon"></span></a>
                    </div>

                </div>


            </div>
        </div>
        <div class="topskew-thumbnail-group almousaid-crea text-left text-lg-right">
            <img src="{{asset('frontend/assets/images/bg/crea01.svg')}}" alt="Almoudaid">
        </div>
    </div>
</div>